export const habitDefinitions = [
    { id: 'pratah', title: 'Pratah Sandhyavandana', target: 'Completion required', category: 'core', type: 'boolean', essential: true },
    { id: 'sayam', title: 'Sayam Sandhyavandana', target: 'Completion required', category: 'core', type: 'boolean', essential: false },
    { id: 'japa', title: 'Japa / Meditation (Optional)', target: 'Any duration', category: 'growth', type: 'boolean', essential: false },
    { id: 'prayoga', title: 'Baudhāyanīya Prayoga', target: '30 mins', category: 'study', type: 'number', minNormal: 30, minBusy: 15, essential: true },
    { id: 'nyaya', title: 'Nyaya Shastra', target: 'Minimum 1 page', category: 'study', type: 'number', minNormal: 1, minBusy: 0.5, essential: true },
    { id: 'mimamsa', title: 'Mimamsa Shastra', target: 'Minimum 1 page', category: 'study', type: 'number', minNormal: 1, minBusy: 0.5, essential: true },
    { id: 'learning', title: 'New Learning', target: '15-30 mins (Log in Journal)', category: 'growth', type: 'boolean', essential: false },
    { id: 'teaching', title: 'Teaching Preparation', target: 'Completion', category: 'core', type: 'boolean', essential: false },
    { id: 'family', title: 'Family Time', target: 'Meaningful presence (~30 mins)', category: 'core', type: 'boolean', essential: true },
    { id: 'digital', title: 'Digital Discipline', target: 'Avoided unnecessary scrolling', category: 'lifestyle', type: 'boolean', essential: false },
    { id: 'review', title: 'Night Review', target: 'Reflection (Log in Reviews)', category: 'core', type: 'boolean', essential: true },
    { id: 'sleep', title: 'Adequate Sleep', target: '~7 hours', category: 'lifestyle', type: 'boolean', essential: true }
];

export const subhashitas = [
    // Days 1-30: Foundation & Action
    { quote: "ಉದ್ಯಮೇನ ಹಿ ಸಿಧ್ಯಂತಿ ಕಾರ್ಯಾಣಿ ನ ಮನೋರಥೈಃ |", meaning: "Effort alone brings success, not mere wishes. (ಪ್ರಯತ್ನದಿಂದ ಮಾತ್ರ ಯಶಸ್ಸು)" },
    { quote: "Discipline is keeping a promise to yourself.", meaning: "ಶಿಸ್ತು ಎಂದರೆ ತನಗೆ ತಾನು ನೀಡಿದ ಭರವಸೆಯನ್ನು ಉಳಿಸಿಕೊಳ್ಳುವುದು." },
    { quote: "ಕ್ಷಣಶಃ ಕಣಶಶ್ಚೈವ ವಿದ್ಯಾಮರ್ಥಂ ಚ ಸಾಧಯೇತ್ |", meaning: "Knowledge is acquired moment by moment. (ಕ್ಷಣಕ್ಷಣವೂ ವಿದ್ಯೆ ಗಳಿಸಬೇಕು)" },
    { quote: "Never miss twice.", meaning: "ಒಂದು ದಿನ ತಪ್ಪಿದರೂ, ಮರುದಿನ ಖಂಡಿತ ಮರಳಬೇಕು." },
    { quote: "ನ ಹಿ ಸುಪ್ತಸ್ಯ ಸಿಂಹಸ್ಯ ಪ್ರವಿಶಂತಿ ಮುಖೇ ಮೃಗಾಃ |", meaning: "Action is required; prey does not enter a sleeping lion's mouth." },
    { quote: "Protect the habit, reduce the size.", meaning: "ಕಷ್ಟದ ದಿನಗಳಲ್ಲಿ ಅಭ್ಯಾಸದ ಪ್ರಮಾಣವನ್ನು ಕಡಿಮೆ ಮಾಡಿ, ಆದರೆ ಬಿಡಬೇಡಿ." },
    { quote: "ಮಾತೃದೇವೋ ಭವ | ಪಿತೃದೇವೋ ಭವ |", meaning: "Revere your parents. Family is the core discipline." },
    { quote: "Consistency beats intensity.", meaning: "ಒಂದೇ ದಿನ ಅತಿ ಹೆಚ್ಚು ಮಾಡುವುದಕ್ಕಿಂತ ಪ್ರತಿದಿನ ಸ್ವಲ್ಪ ಮಾಡುವುದು ಶ್ರೇಷ್ಠ." },
    { quote: "ಕಾಲಾಯ ತಸ್ಮೈ ನಮಃ |", meaning: "Salutations to Time. Use it wisely today." },
    { quote: "Sleep is the foundation of discipline.", meaning: "ಸಾಕಷ್ಟು ನಿದ್ರೆಯಿಲ್ಲದೆ ಶಿಸ್ತು ಸಾಧ್ಯವಿಲ್ಲ." },
    { quote: "ವಿದ್ಯಾ ದದಾತಿ ವಿನಯಂ |", meaning: "True knowledge brings humility and discipline." },
    { quote: "Small daily progress leads to staggering results.", meaning: "ಸಣ್ಣ ದೈನಂದಿನ ಪ್ರಗತಿಯು ಆಶ್ಚರ್ಯಕರ ಫಲಿತಾಂಶಗಳನ್ನು ತರುತ್ತದೆ." },
    { quote: "ಅಲಸಸ್ಯ ಕುತೋ ವಿದ್ಯಾ |", meaning: "Where is knowledge for the lazy?" },
    { quote: "Do not wait for perfect conditions. Begin.", meaning: "ಪರಿಪೂರ್ಣ ಸಮಯಕ್ಕಾಗಿ ಕಾಯಬೇಡಿ. ಪ್ರಾರಂಭಿಸಿ." },
    { quote: "ಶ್ರದ್ಧಾವಾನ್ ಲಭತೇ ಜ್ಞಾನಮ್ |", meaning: "The one with absolute focus and faith attains knowledge." },
    { quote: "Your routine is your destiny.", meaning: "ನಿಮ್ಮ ದಿನಚರಿಯೇ ನಿಮ್ಮ ಭವಿಷ್ಯ." },
    { quote: "ಯೋಗಃ ಕರ್ಮಸು ಕೌಶಲಮ್ |", meaning: "Yoga is excellence in action. Do today's work perfectly." },
    { quote: "Discipline equals freedom.", meaning: "ಶಿಸ್ತು ಎಂದರೆ ಸ್ವಾತಂತ್ರ್ಯ." },
    { quote: "ಆಲಸ್ಯಂ ಹಿ ಮನುಷ್ಯಾಣಾಂ ಶರೀರಸ್ಥೋ ಮಹಾನ್ ರಿಪುಃ |", meaning: "Laziness is the greatest enemy residing in the body." },
    { quote: "Show up. Even on the hard days.", meaning: "ಕಷ್ಟದ ದಿನಗಳಲ್ಲೂ ಕೆಲಸವನ್ನು ತಪ್ಪಿಸದಿರಿ." },
    { quote: "ಧರ್ಮೇ ಜಾಗೃತ ಜಾಗೃತ |", meaning: "Awake and be vigilant in your duties." },
    { quote: "Master the morning, master the day.", meaning: "ಬೆಳಗಿನ ಜಾವವನ್ನು ಗೆದ್ದವನು ದಿನವನ್ನು ಗೆಲ್ಲುತ್ತಾನೆ." },
    { quote: "ಸತ್ಯಂ ವದ | ಧರ್ಮಂ ಚರ |", meaning: "Speak truth. Walk the path of duty." },
    { quote: "Focus on the root, the fruit will follow.", meaning: "ಬೇರಿನ ಕಡೆ ಗಮನ ಕೊಡಿ, ಹಣ್ಣು ತಾನಾಗಿಯೇ ಬರುತ್ತದೆ." },
    { quote: "ಉತ್ತಿಷ್ಠತ ಜಾಗ್ರತ ಪ್ರಾಪ್ಯ ವರಾನ್ನಿಬೋಧತ |", meaning: "Arise, awake, and stop not till the goal is reached." },
    { quote: "You are what you repeatedly do.", meaning: "ನೀವು ಪದೇ ಪದೇ ಏನು ಮಾಡುತ್ತೀರೋ, ಅದೇ ನೀವು." },
    { quote: "ಕರ್ಮಣ್ಯೇವಾಧಿಕಾರಸ್ತೇ ಮಾ ಫಲೇಷು ಕದಾಚನ |", meaning: "You have a right to perform your duty, but not to the fruits." },
    { quote: "A 30-minute study today is better than 3 hours tomorrow.", meaning: "ನಾಳೆ ಮಾಡುವ ೩ ಗಂಟೆಯ ಅಧ್ಯಯನಕ್ಕಿಂತ, ಇಂದು ಮಾಡುವ ೩೦ ನಿಮಿಷದ ಅಧ್ಯಯನ ಮೇಲು." },
    { quote: "ಸ್ವಲ್ಪಮಪ್ಯಸ್ಯ ಧರ್ಮಸ್ಯ ತ್ರಾಯತೇ ಮಹತೋ ಭಯಾತ್ |", meaning: "Even a little of this discipline protects one from great fear." },
    { quote: "Day 30. The foundation is built. Keep going.", meaning: "೩೦ನೇ ದಿನ. ತಳಪಾಯ ಸಿದ್ಧವಾಗಿದೆ. ಮುಂದುವರಿಯಿರಿ." },

    // Days 31-60: Consistency & Endurance
    { quote: "ಅಭ್ಯಾಸೇನ ತು ಕೌಂತೇಯ ವೈರಾಗ್ಯೇಣ ಚ ಗೃಹ್ಯತೇ |", meaning: "Through practice and detachment, the mind is controlled." },
    { quote: "The middle of the journey is the hardest. Stay the course.", meaning: "ಪ್ರಯಾಣದ ಮಧ್ಯಭಾಗವು ಕಠಿಣ. ಆದರೆ ಗುರಿ ಬಿಡದಿರಿ." },
    { quote: "ಯದ್ಭಾವಂ ತದ್ಭವತಿ |", meaning: "You become what you believe and practice." },
    { quote: "Don't negotiate with your mind. Just execute.", meaning: "ಮನಸ್ಸಿನೊಂದಿಗೆ ಚೌಕಾಸಿ ಮಾಡಬೇಡಿ. ಕೆಲಸ ಮಾಡಿ." },
    { quote: "ನಾಸ್ತಿ ಬುದ್ಧಿರಯುಕ್ತಸ್ಯ |", meaning: "There is no intelligence without discipline." },
    { quote: "Tired? Learn to rest, not to quit.", meaning: "ಆಯಾಸವಾದರೆ ವಿಶ್ರಮಿಸಲು ಕಲಿಯಿರಿ, ಬಿಟ್ಟುಬಿಡಲು ಅಲ್ಲ." },
    { quote: "ಜಿತ್ವಾತ್ಮಾನಂ ಜಯೇತ್ ಜಗತ್ |", meaning: "Conquer yourself to conquer the world." },
    { quote: "A Minimum Day is a victory of character.", meaning: "ಕಷ್ಟದ ದಿನದಲ್ಲೂ ಕನಿಷ್ಠ ಕೆಲಸ ಮಾಡುವುದು ನಿಮ್ಮ ವ್ಯಕ್ತಿತ್ವದ ಗೆಲುವು." },
    { quote: "ಬುದ್ಧಿರ್ಯಸ್ಯ ಬಲಂ ತಸ್ಯ |", meaning: "He who has intelligence has true strength." },
    { quote: "Avoid digital distractions. Protect your attention.", meaning: "ಮೊಬೈಲ್ ಗೀಳಿನಿಂದ ದೂರವಿರಿ. ನಿಮ್ಮ ಏಕಾಗ್ರತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ." },
    { quote: "ಆಚಾರಃ ಪರಮೋ ಧರ್ಮಃ |", meaning: "Right conduct is the highest duty." },
    { quote: "Study Shastra not for exams, but for life.", meaning: "ಶಾಸ್ತ್ರವನ್ನು ಪರೀಕ್ಷೆಗಾಗಿ ಅಲ್ಲ, ಜೀವನಕ್ಕಾಗಿ ಓದಿ." },
    { quote: "ತಮಸೋ ಮಾ ಜ್ಯೋತಿರ್ಗಮಯ |", meaning: "Lead me from darkness to light through daily study." },
    { quote: "Family time is an investment, not an interruption.", meaning: "ಕುಟುಂಬದೊಂದಿಗಿನ ಸಮಯ ಒಂದು ಹೂಡಿಕೆ, ಅಡಚಣೆಯಲ್ಲ." },
    { quote: "ವಿದ್ಯಾ ಧನಂ ಸರ್ವಧನಾತ್ ಪ್ರಧಾನಮ್ |", meaning: "The wealth of knowledge is supreme." },
    { quote: "Look at your streak. Honor the work you've done.", meaning: "ನಿಮ್ಮ ಸತತ ಪ್ರಯತ್ನವನ್ನು ಗೌರವಿಸಿ. ಅದನ್ನು ಮುರಿಯದಿರಿ." },
    { quote: "ಶಾಂತಂ ಪಾಪಂ |", meaning: "Let the mind be peaceful and focused." },
    { quote: "Momentum is built drop by drop.", meaning: "ಹನಿಹನಿಯಾಗಿ ಶಕ್ತಿ ಬೆಳೆಯುತ್ತದೆ." },
    { quote: "ಶರೀರಮಾಧ್ಯಂ ಖಲು ಧರ್ಮಸಾಧನಮ್ |", meaning: "The body is the primary instrument of discipline." },
    { quote: "Respect your Sandhyavandana. It roots the day.", meaning: "ಸಂಧ್ಯಾವಂದನೆಯು ದಿನದ ಆಧಾರ. ಅದನ್ನು ಗೌರವಿಸಿ." },
    { quote: "ಯಥಾ ದೃಷ್ಟಿಸ್ತಥಾ ಸೃಷ್ಟಿಃ |", meaning: "As is your vision, so is your world." },
    { quote: "Don't complain about the work you chose.", meaning: "ನೀವೇ ಆರಿಸಿಕೊಂಡ ಕೆಲಸದ ಬಗ್ಗೆ ದೂಷಿಸದಿರಿ." },
    { quote: "ಮಹಾಜನೋ ಯೇನ ಗತಃ ಸ ಪಂಥಾಃ |", meaning: "Follow the path walked by the great ones." },
    { quote: "Today is the only day you can control.", meaning: "ಇಂದಿನ ದಿನವನ್ನು ಮಾತ್ರ ನೀವು ನಿಯಂತ್ರಿಸಬಹುದು." },
    { quote: "ವಿದ್ವಾನ್ ಸರ್ವತ್ರ ಪೂಜ್ಯತೇ |", meaning: "A scholar is respected everywhere." },
    { quote: "Review your day honestly. Growth requires truth.", meaning: "ನಿಮ್ಮ ದಿನವನ್ನು ಪ್ರಾಮಾಣಿಕವಾಗಿ ವಿಮರ್ಶಿಸಿ." },
    { quote: "ಸತತಂ ಕಾರ್ಯಂ ಕರ್ಮ ಸಮಾಚರ |", meaning: "Always perform your duty efficiently." },
    { quote: "The mind will seek excuses. Give it tasks instead.", meaning: "ಮನಸ್ಸು ನೆಪಗಳನ್ನು ಹುಡುಕುತ್ತದೆ. ಅದಕ್ಕೆ ಕೆಲಸ ಕೊಡಿ." },
    { quote: "ಏಕಮೇವ ಅದ್ವಿತೀಯಂ |", meaning: "Focus on the ONE most important task today." },
    { quote: "Day 60. Consistency achieved. Now, mastery.", meaning: "೬೦ನೇ ದಿನ. ನಿರಂತರತೆ ಸಾಧಿಸಿದ್ದೀರಿ. ಈಗ ಪ್ರಾವೀಣ್ಯತೆಯತ್ತ." },

    // Days 61-90: Mastery & Internalization
    { quote: "ಜ್ಞಾನದೇವೇನ ಮೋಕ್ಷಃ |", meaning: "Liberation comes through knowledge alone." },
    { quote: "Discipline is no longer a task. It is your nature.", meaning: "ಶಿಸ್ತು ಈಗ ಒಂದು ಕೆಲಸವಲ್ಲ. ಅದು ನಿಮ್ಮ ಸ್ವಭಾವ." },
    { quote: "ಮನ ಏವ ಮನುಷ್ಯಾಣಾಂ ಕಾರಣಂ ಬಂಧಮೋಕ್ಷಯೋಃ |", meaning: "The mind alone is the cause of bondage and liberation." },
    { quote: "Deep study requires deep stillness.", meaning: "ಆಳವಾದ ಅಧ್ಯಯನಕ್ಕೆ ಆಳವಾದ ಶಾಂತಿ ಬೇಕು." },
    { quote: "ಸರ್ವೇ ಭವಂತು ಸುಖಿನಃ |", meaning: "May all be happy. (Work for the greater good)." },
    { quote: "A scholar's true weapon is his focus.", meaning: "ವಿದ್ವಾಂಸನ ನಿಜವಾದ ಆಯುಧ ಅವನ ಏಕಾಗ್ರತೆ." },
    { quote: "ಸತ್ಯಮೇವ ಜಯತೇ ನಾನೃತಂ |", meaning: "Truth alone triumphs, not falsehood." },
    { quote: "Every page of Nyaya sharpens the intellect.", meaning: "ನ್ಯಾಯಶಾಸ್ತ್ರದ ಪ್ರತಿಯೊಂದು ಪುಟವೂ ಬುದ್ಧಿಯನ್ನು ಚುರುಕುಗೊಳಿಸುತ್ತದೆ." },
    { quote: "ಧರ್ಮೋ ರಕ್ಷತಿ ರಕ್ಷಿತಃ |", meaning: "Dharma protects those who protect it." },
    { quote: "Your family observes your discipline. Lead by example.", meaning: "ನಿಮ್ಮ ಶಿಸ್ತನ್ನು ನಿಮ್ಮ ಕುಟುಂಬ ಗಮನಿಸುತ್ತದೆ. ಮಾದರಿಯಾಗಿರಿ." },
    { quote: "ಆರೋಗ್ಯಂ ಭಾಸ್ಕರಾದಿಚ್ಛೇತ್ |", meaning: "Seek health from the Sun. (Value your mornings)." },
    { quote: "Keep the system simple. Execute flawlessly.", meaning: "ವ್ಯವಸ್ಥೆಯನ್ನು ಸರಳವಾಗಿಡಿ. ಅದ್ಭುತವಾಗಿ ಕಾರ್ಯಗತಗೊಳಿಸಿ." },
    { quote: "ಗುರುಬ್ರಹ್ಮಾ ಗುರುರ್ವಿಷ್ಣುಃ |", meaning: "Revere the Teacher. Become a worthy student." },
    { quote: "True learning changes behavior.", meaning: "ನಿಜವಾದ ಕಲಿಕೆ ನಡವಳಿಕೆಯನ್ನು ಬದಲಾಯಿಸುತ್ತದೆ." },
    { quote: "ವಿನಯಾತ್ ಯಾತಿ ಪಾತ್ರತಾಮ್ |", meaning: "Humility leads to worthiness." },
    { quote: "Do not let success make you lazy.", meaning: "ಯಶಸ್ಸು ನಿಮ್ಮನ್ನು ಸೋಮಾರಿಯನ್ನಾಗಿ ಮಾಡದಿರಲಿ." },
    { quote: "ಸುಖಸ್ಯ ಮೂಲಂ ಧರ್ಮಃ |", meaning: "The root of happiness is Dharma (duty)." },
    { quote: "Mimamsa structures the mind. Study it closely.", meaning: "ಮೀಮಾಂಸಾ ಶಾಸ್ತ್ರವು ಮನಸ್ಸನ್ನು ರೂಪಿಸುತ್ತದೆ. ಆಳವಾಗಿ ಅಧ್ಯಯನ ಮಾಡಿ." },
    { quote: "ಧರ್ಮಸ್ಯ ಮೂಲಂ ಅರ್ಥಃ |", meaning: "The root of duty is proper management of resources." },
    { quote: "Protect your sleep. It protects your discipline.", meaning: "ನಿಮ್ಮ ನಿದ್ರೆಯನ್ನು ರಕ್ಷಿಸಿ. ಅದು ನಿಮ್ಮ ಶಿಸ್ತನ್ನು ರಕ್ಷಿಸುತ್ತದೆ." },
    { quote: "ಅರ್ಥಸ್ಯ ಮೂಲಂ ರಾಜ್ಯಮ್ |", meaning: "The root of resources is good governance (self-governance)." },
    { quote: "The 90-day mark is near. Finish strong.", meaning: "೯೦ನೇ ದಿನ ಹತ್ತಿರದಲ್ಲಿದೆ. ದೃಢವಾಗಿ ಪೂರ್ಣಗೊಳಿಸಿ." },
    { quote: "ರಾಜ್ಯಸ್ಯ ಮೂಲಂ ಇಂದ್ರಿಯಜಯಃ |", meaning: "The root of self-governance is the conquest of senses." },
    { quote: "You are proving to yourself who you are.", meaning: "ನೀವು ಯಾರೆಂದು ನಿಮಗೆ ನೀವೇ ಸಾಬೀತುಪಡಿಸುತ್ತಿದ್ದೀರಿ." },
    { quote: "ಇಂದ್ರಿಯಜಯಸ್ಯ ಮೂಲಂ ವಿನಯಃ |", meaning: "The root of sense-conquest is humility." },
    { quote: "Do the work quietly. Let the results speak.", meaning: "ಕೆಲಸವನ್ನು ಮೌನವಾಗಿ ಮಾಡಿ. ಫಲಿತಾಂಶವೇ ಮಾತನಾಡಲಿ." },
    { quote: "ವಿನಯಸ್ಯ ಮೂಲಂ ವೃದ್ಧೋಪಸೇವಾ |", meaning: "The root of humility is serving the elders/teachers." },
    { quote: "You have built the habit. Now, live the habit.", meaning: "ನೀವು ಅಭ್ಯಾಸವನ್ನು ಬೆಳೆಸಿದ್ದೀರಿ. ಈಗ ಅದನ್ನು ಜೀವಿಸಿ." },
    { quote: "ವಿಜ್ಞಾನಂ ಬ್ರಹ್ಮೇತಿ ವ್ಯಜಾನಾತ್ |", meaning: "He knew that Knowledge is Brahman." },
    { quote: "Day 90. This is not the end. It is your new beginning.", meaning: "೯೦ನೇ ದಿನ. ಇದು ಅಂತ್ಯವಲ್ಲ. ಇದು ನಿಮ್ಮ ಹೊಸ ಆರಂಭ." }
];
